name: monobank_api_corp
description: >
    Server-side library for Monobank Open API for providers (Corp)

    Relevant signature crypto, etc. Companion library for monobank_api
version: 3.0.0
repository: https://github.com/Sominemo/monobank_api_corp

environment:
    sdk: ">=2.17.0 <4.0.0"

dependencies:
    monobank_api: ">=3.0.1 <4.0.0"
    crypto: ^3.0.0
    ecdsa: ^0.1.2
    elliptic: ^0.3.9

dev_dependencies:
    lints: ^4.0.0
